don't obtain translate method from get_localizer if request is None
this would break in pyramid.i18n with:
AttributeError: 'NoneType' object has no attribute 'locale_name'